slack:
    token: xoxb-463301830065-464800823138-Uj1cSkdQHzZXc5m29QAF6sn7
    base_url: https://toolsforhumans.slack.com/

admin_channel: "test-bot"
periodic_channel: "test-bot"

ansible:
    host_key_checking: false

logging:
    version: 1
    formatters:
        standard:
            format: "%(asctime)-15s %(levelname)s:%(name)s:%(message)s"
    loggers:
        requests:
            handlers: [console]
            level: WARN
            propagate: false
        urllib3:
            handlers: [console]
            level: WARN
            propagate: false
        padre:
            handlers: [console]
            level: DEBUG
            propagate: false
    root:
        handlers: [console]
        level: ERROR
    handlers:
        console:
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: standard

snow:
    environment: "test"
    unfurl: false

working_dir: "/Users/clintb/tmp/daddy/"
persistent_working_dir: "/Users/clintb/tmp/daddy/"
playbook_dir: ""
env_dir: ""
ansible_config_path: "/Users/clintb/tmp/daddy/ansible.cfg"
template_dirs:
    - "templates"
statics_dir: "static"
hostname: "localhost"

# Easier to access this (without root needed).
status:
    port: 4080
